---
- name: "Newbler"
  startCommand: "runAssembler"
  outputEndings:
  - ".fa"
  onlyOutputDirectorySetable: true
  enterCommand: "newbler enter command"
  exitCommand: "newbler exit command"
  parameters:
  - name: "outputPathCommand"
    command: "-o"
    position: 0
    optional: false
  - name: "inputPathCommand"
    command: "-p"
    position: -1
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "-o"
    position: 0
    optional: false
  essentialOutputs: []
  validInputEndings:
  - ".fa"
  - ".fastq"
- name: "Allpath"
  startCommand: "apply startCommand"
  outputEndings:
  - ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "outputPathCommand"
    command: "apply outputPathCommand"
    position: 0
    optional: false
  - name: "inputPathCommand"
    command: "apply inputPathCommand"
    position: -1
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "apply outputPathCommand"
    position: 0
    optional: false
  essentialOutputs: []
  validInputEndings:
  - ".fa"
  - ".fastq"
- name: "Choose non"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    position: 0
    optional: false
  - name: "outputPathCommand"
    position: 0
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    position: 0
    optional: false
  essentialOutputs: []