---
- name: "Newbler"
  startCommand: "/vol/454/.old/2.8/bin/runAssembly"
  outputEndings:
  - ".fna"
  - ".fa"
  - ".txt"
  onlyOutputDirectorySetable: true
  parameters:
  - name: "outputPathCommand"
    command: "-o"
    position: 0
    optional: false
  - name: "inputPathCommand"
    position: -1
    optional: false
  - name: "large"
    command: "-large"
    defaultValue: "/empty"
    position: 1
    optional: true
  - name: "CPU"
    command: "-cpu"
    defaultValue: "0"
    position: 2
    optional: true
  - name: "Force"
    command: "-force"
    defaultValue: "/empty"
    position: 3
    optional: false
  essentialOutputs:
  - dynamic: false
    essentialFor: "Assembly Statistics"
    useAll: false
    useOnly: true
    name: "//."
    lowerbound: 0
    upperbound: 0
  - dynamic: false
    essentialFor: "defaultProdigal"
    useAll: false
    useOnly: true
    name: "454AllContigs.fna"
    lowerbound: 0
    upperbound: 0
  validInputEndings:
  - ".fa"
  - ".fastq"
- name: "Allpath"
  startCommand: "apply startCommand"
  outputEndings:
  - ".fna"
  - ".fa"
  - ".txt"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "outputPathCommand"
    command: "apply outputPathCommand"
    position: 0
    optional: false
  - name: "inputPathCommand"
    command: "apply inputPathCommand"
    position: -1
    optional: false
  essentialOutputs: []
  validInputEndings:
  - ".fa"
  - ".fastq"
- name: "Choose non"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    position: 0
    optional: false
  - name: "outputPathCommand"
    position: 0
    optional: false
  essentialOutputs: []