---
- name: "MiSeqFASTQ4Newbler_v2.8b"
  startCommand: "SCRITPS/MiSeqFASTQ4Newbler_v2.8b_OutputOnArgs1.pl"
  outputEndings:
  - ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    position: 1
    optional: false
  - name: "outputPathCommand"
    position: 2
    optional: false
  essentialOutputs: []
  validInputEndings:
  - ".fastq"
- name: "split_MiSeq_MP_nextera"
  startCommand: "SCRITPS/split_MiSeq_MP_nextera_OutputOnArgs1.pl"
  outputEndings:
  - ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    position: 1
    optional: false
  - name: "outputPathCommand"
    position: 2
    optional: false
  essentialOutputs: []
  validInputEndings:
  - ".fastq"
- name: "Choose non"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    position: 0
    optional: false
  - name: "outputPathCommand"
    position: 0
    optional: false
  essentialOutputs: []