---
- name: "defaultReadsVsContigs"
  startCommand: "run reads vs contigs"
  outputEndings:
  - ".fa"
  onlyOutputDirectorySetable: false
  enterCommand: "reads vs contigs enter command"
  exitCommand: " reads vs contigs exit command"
  parameters:
  - name: "outputPathCommand"
    command: "-out something"
    position: 0
    optional: false
  - name: "inputPathCommand"
    command: "-in something"
    position: -1
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "-out something"
    position: 0
    optional: false
  validInputEndings:
  - ".fa"
  - ".fq"