---
- name: "Example Tool 1"
  startCommand: "start Tool 1"
  outputEnding: ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    command: "apply inputCommand Tool 1"
    position: 0
    optional: false
  - name: "outputPathCommand"
    command: "apply outputCommand Tool 1"
    position: -1
    optional: false
  - name: "Test Boolean"
    command: "boolean value"
    defaultValue: "/empty"
    position: 1
    optional: true
  - name: "Test optional"
    command: "optional value"
    defaultValue: "Test optional default"
    position: 2
    optional: true
  - name: "Test obligatory"
    command: "obligatory value"
    defaultValue: "Test obligatory default"
    position: 3
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "apply outputCommand Tool 1"
    position: -1
    optional: false
  validInputEndings:
  - ".fa"
- name: "Example Tool 2"
  startCommand: "start Tool 2"
  outputEnding: ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    command: "apply inputCommand Tool 2"
    position: 0
    optional: false
  - name: "outputPathCommand"
    command: "apply outputCommand Tool 2"
    position: 0
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "apply outputCommand Tool 2"
    position: 0
    optional: false
  validInputEndings:
  - ".fa"
- name: "Example Tool 3"
  startCommand: "start Tool 3"
  outputEnding: ".fa"
  onlyOutputDirectorySetable: false
  parameters:
  - name: "inputPathCommand"
    command: "apply inputCommand Tool 3"
    position: 0
    optional: false
  - name: "outputPathCommand"
    command: "apply outputCommand Tool 3"
    position: 0
    optional: false
  outputPathCommand:
    name: "outputPathCommand"
    command: "apply outputCommand Tool 3"
    position: 0
    optional: false
  validInputEndings:
  - ".fa"